proj/elite3eloader/urls.py
from django.contrib import admin
from django.urls import path, include
from junction.core.views import index, junction_license, backup_create, backup


urlpatterns = [
    path('admin/', admin.site.urls),
    path('servers/', include('junction.servers.urls', namespace='servers')),
    path('loaders/', include('junction.loaders.urls', namespace='loaders')),
    path('license/', junction_license, name='license'),
    path('backup/', backup, name='backup'),
    path('backup-create/', backup_create, name='backup_create'),
    path('', index, name='index'),
]

proj/junction/loaders/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright 2018 Junction Applications
# Author: Aaron MacGillivary
# Project: elite3eloader

from . import views
from django.urls import path

app_name = 'loaders'

urlpatterns = [
    path('', views.loader_list, name='loader_list'),
    path('new/', views.loader_edit, name='loader_edit'),
    path('<slug:loader_slug>/run', views.loader_run, name='loader_run'),
    path('<slug:loader_slug>', views.loader_edit, name='loader_edit'),
    path('<slug:loader_slug>/tab/attributes/', views.loader_edit, {'active_tab': 'Attributes'},  name='loader_attribute_active'),
    path('<slug:loader_slug>/tab/advanced/', views.loader_edit, {'active_tab': 'Advanced'},  name='loader_advanced_active'),
    path('<slug:loader_slug>/attribute/<slug:attribute_slug>', views.loader_edit, name='attribute_edit'),
    path('<slug:loader_slug>/xoql/<slug:loaderxoql_slug>', views.loader_edit, name='loaderxoql_edit'),
    path('<slug:loader_slug>/history/request/<int:pk>', views.history_raw, name='loader_history_request'),
    path('<slug:loader_slug>/runxoql/', views.run_xoql, name='run_xoql'),

]

proj/junction/loaders/models.py
import json
from django.db import models
from django.utils.text import slugify

from junction.servers.models import Server
import xml.etree.ElementTree as ET


class Loader(models.Model):

    ADD = 'Add'
    EDIT = 'Edit'
    ACTION_CHOICES = (
        (ADD, 'Add'),
        (EDIT, 'Edit'),
    )
    """ The list of available loaders. """
    name = models.CharField(max_length=64, unique=True, help_text='Common name for this loader')
    description = models.TextField(blank=True, null=True, help_text="Description of this loader's purpose")
    active = models.BooleanField(default=True)
    parent_action = models.CharField(max_length=64, choices=ACTION_CHOICES, default=EDIT, help_text="The type of action this loader performs")
    parent_object = models.CharField(max_length=256, help_text="The primary object we are action upon")

    child_action = models.CharField(max_length=64, null=True, blank=True, choices=ACTION_CHOICES, default=ADD, help_text="If applicable, the child action to be performed")
    child_object = models.CharField(max_length=256, null=True, blank=True, help_text="If applicable, the child object we are acting upon")

    last_run = models.DateTimeField(blank=True, null=True)
    process = models.CharField(max_length=256, help_text='The 3E process which this loader will call')

    slug = models.SlugField(unique=True)

    def __str__(self):
        return f"{self.name}"

    def save(self, *args, **kwargs):
        # create a unique slug for this record
        suffix = 0
        potential = base = slugify(f'{self.name[:50]}')
        self.slug = None
        while not self.slug:
            if suffix:
                potential = f'{base}-{suffix}'
            if not Loader.objects.filter(slug=potential).exists():
                self.slug = potential
            suffix += 1

        super(Loader, self).save(*args, **kwargs)


class LoaderXOQL(models.Model):
    """
    An optional advanced listing of xoql to initially fill the data table with data.
    Originally used in testing, but thought to be useful in a variety of use cases.
    It is suggested to use Thomson's OQL Analyser to write the code, compile and modify the
    the resulting xoql accordingly. Fields that correspond to fields in the datatable will
    be filled in with data from 3E. Keep in mind that the results can repeating nodes with
    the same name; the responsibility lies with you to ensure uniqueness. Use the Alias attribute
    to name to match the Attributes in the Loader setup.

    In the value nodes, use the Alias attribute in the LEAF node.
    <VALUE>
      <LEAF QueryID="Description" Alias="TkprDate__Title1__Description">
        <NODE NodeID="Title1" />
      </LEAF>
    </VALUE>
    """
    loader = models.ForeignKey(Loader, on_delete=models.CASCADE)
    name = models.CharField(max_length=64, help_text="A name for this xoql")
    description = models.TextField(blank=True, null=True, help_text="A brief description for this loader")
    xoql = models.TextField(blank=True, null=True, help_text="The xoql to populate the data table on Run tab",
                            verbose_name="XOQL")
    slug = models.SlugField()

    def __str__(self):
        return f"{self.name}"

    def save(self, *args, **kwargs):
        # create a unique slug for this record
        suffix = 0
        potential = base = slugify(f'{self.name[:50]}')
        self.slug = None
        while not self.slug:
            if suffix:
                potential = f'{base}-{suffix}'
            if not LoaderXOQL.objects.filter(slug=potential).exists():
                self.slug = potential
            suffix += 1

        super(LoaderXOQL, self).save(*args, **kwargs)


class Attribute(models.Model):
    """ The attributes on a particular load. """
    CHILD = 'Child'
    PARENT = 'Parent'
    TYPE_CHOICES = (
        (CHILD, CHILD),
        (PARENT, PARENT),
    )

    DISPLAY_ONLY = 'Display'
    LOADER_XML = 'Export'
    INCLUDE_CHOICES = ((DISPLAY_ONLY, 'Show in Display only'),
                       (LOADER_XML, 'Display and include in Loader XML'),)
    loader = models.ForeignKey(Loader, on_delete=models.CASCADE)
    name = models.CharField(max_length=64, help_text='The name of the attribute (case sensitive)')
    type = models.CharField(max_length=64, help_text='Does this belong to the parent object or the child?', default=CHILD, choices=TYPE_CHOICES)
    sort = models.IntegerField(default=1, help_text='Numerical value to control the order of the fields')
    is_key = models.BooleanField(default=False, help_text='Select for a key field')
    include_type = models.CharField(default=LOADER_XML, max_length=64, choices=INCLUDE_CHOICES, help_text='Controls if this is a display only field, or included in the loader.')
    alias_field = models.CharField(max_length=256, blank=True, null=True, help_text='If provided, will be used as the AliasField')
    slug = models.SlugField()
    active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.loader.name} - {self.name}'

    def save(self, *args, **kwargs):
        # create a unique slug for this record on each save - simply for url friendliness
        # keep in mind that the slug is unique but can change on save
        suffix = 0
        potential = base = slugify(f'{self.name[:40]}')
        self.slug = None
        while not self.slug:
            if suffix:
                potential = f'{base}-{suffix}'
            if not Loader.objects.filter(slug=potential).exists():
                self.slug = potential
            suffix += 1

        super(Attribute, self).save(*args, **kwargs)

    class Meta:
        unique_together = ('name', 'loader')
        ordering = ('sort', 'name')


class AvailableAttribute(models.Model):
    """ A list of available object attributes """
    name = models.CharField(max_length=64, help_text='The field or attribute id from the object')
    alias_field = models.CharField(max_length=256, blank=True, null=True)

    def __str__(self):
        return f'{self.name}'


class History(models.Model):
    loader = models.ForeignKey(Loader, on_delete=models.PROTECT, help_text="Select a server to push the data")
    column_headers = models.TextField(blank=True, null=True)
    data = models.TextField(blank=True, null=True)
    server = models.ForeignKey(Server, on_delete=models.PROTECT)
    process_xml = models.TextField(blank=True, null=True)
    submitted = models.DateTimeField(auto_now_add=True)
    response = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.loader.name} - {self.submitted}"

    def number_of_records(self):
        return len(json.loads(self.data)['data'])

    def elite_attributes(self):
        # {'Process': '', 'Result': '', 'StepId': '', 'Records': '', 'User': '', 'Name': '', 'ProcessItemId': ''}
        # {'Result': "Failure", Message:"Error attempting to read data."}
        return ET.fromstring(self.response).attrib

    def elite_attribute(self, attribute):
        try:
            return self.elite_attributes()[attribute]
        except KeyError:
            return None

    def elite_process(self):
        return self.elite_attribute("Process")

    def elite_results(self):
        return self.elite_attribute("Result")

    def elite_records(self):
        return self.elite_attribute("Records")

    def elite_message(self):
        return self.elite_attribute("Message")

    def elite_data_errors(self):
        root = ET.fromstring(self.response)
        return '\n'.join([e.text for e in root.iter('E')])

    @staticmethod
    def beautify(ugly):
        from lxml import etree
        parser = etree.XMLParser(remove_blank_text=True)
        tree = etree.fromstring(ugly, parser)
        pretty = etree.tostring(tree, pretty_print=True,
                                xml_declaration=False,
                                encoding='unicode')
        return f"{str(pretty)}"

    def response_pretty(self):
        return self.beautify(self.response)

    def process_xml_pretty(self):
        return self.beautify(self.process_xml)

    def data_pretty(self):
        return json.dumps(self.data, sort_keys=False, indent=2)

    class Meta:
        ordering = ['-submitted',]

proj/junction/loaders/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright 2018 Junction Applications
# Author: Aaron MacGillivary
# Project: elite3eloader

from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm, Form

from junction.loaders.models import Loader, Attribute, History, LoaderXOQL
from junction.servers.models import Server


class HistoryForm(ModelForm):
    xoql = forms.ChoiceField(choices=(), required=False, label='XOQL')

    def __init__(self,*args,**kwargs):
        loader = kwargs.pop('loader', None)
        super (HistoryForm,self ).__init__(*args,**kwargs)
        self.fields['server'].queryset = Server.objects.filter(active=True)
        if loader:
            self.loader = loader
            self.fields['xoql'].choices = LoaderXOQL.objects.filter(loader=loader).values_list('id', 'name')

    class Meta:
        model = History
        fields = ['server', 'data', 'column_headers']
        # 'data', 'column_headers'
        # widgets = {
        #     'data': forms.Textarea(attrs={'rows': 2,}),
        #     'column_headers': forms.Textarea(attrs={'rows': 2, }),
        # }
        widgets = {
            'data': forms.HiddenInput(),
            'column_headers': forms.HiddenInput(),
        }


class LoaderForm(ModelForm):

    class Meta:
        model = Loader
        fields = ['name', 'description', 'process','parent_action', 'parent_object',
                  'child_action', 'child_object', ]
        widgets = {
            'name': forms.TextInput(attrs={'autofocus': 'true', }),
            'description': forms.Textarea(attrs={'rows': 3, })
        }


class AttributeForm(ModelForm):

    def __init__(self, *args, **kwargs):
        loader = kwargs.pop('loader', None)
        super(AttributeForm, self).__init__(*args, **kwargs)
        if loader:
            self.loader = loader

    class Meta:
        model = Attribute
        fields = ['name', 'alias_field', 'is_key', 'type', 'include_type', 'sort',]

    def clean_name(self):
        cleaned_name = self.cleaned_data['name']
        if self.initial['name'] != cleaned_name:
            if Attribute.objects.filter(name=cleaned_name, loader=self.loader).exists():
                raise ValidationError('Attribute with this Name already exists for this loader')

        # Always return cleaned_data
        return cleaned_name


class LoaderXOQLForm(ModelForm):

    def __init__(self, *args, **kwargs):
        loader = kwargs.pop('loader', None)
        super(LoaderXOQLForm, self).__init__(*args, **kwargs)
        if loader:
            self.loader = loader

    class Meta:
        model = LoaderXOQL
        fields = ['name', 'description', 'xoql', ]

        widgets = {
            'name': forms.TextInput(attrs={'autofocus': 'true', }),
            'description': forms.Textarea(attrs={'rows': 2, }),
            'xoql': forms.Textarea(attrs={'class': 'textarea-xml', 'rows': '20', })
        }

    def clean_name(self):
        cleaned_name = self.cleaned_data['name']
        if self.initial['name'] != cleaned_name:
            if LoaderXOQL.objects.filter(name=cleaned_name, loader=self.loader).exists():
                raise ValidationError('XOQL with this Name already exists for this loader')

        return cleaned_name

proj/junction/loaders/templates/loaders/attribute_list.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{#https://simpleisbetterthancomplex.com/article/2017/08/19/how-to-render-django-form-manually.html#}

{% block main_card_header_buttons %}
  <a href="{% url "loaders:loader_edit" %}" class="btn btn-primary btn-round">Add</a>

{% endblock %}

{% block main_content_card_body %}
  <div class="row">
    <div class="col-md-12">
      <table class="table table-hover">
        <thead class=" text-primary">
        <tr>
          <th>
            Name
          </th>
          <th>
            Alias Field
          </th>
        </tr>
        </thead>
        <tbody>

        {% for attribute in attributes %}
          <tr {% if attribute.pk == selected_attribute %}class="table-active"{% endif %}>
            <td><strong><a href="{% url "loaders:attribute_list" attribute.slug %}" >{{ attribute.name }}</a></strong></td>
            <td>{{ attribute.alias_field }}</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>

  </div>
{% endblock %}

proj/junction/loaders/templates/loaders/edit.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{#https://simpleisbetterthancomplex.com/article/2017/08/19/how-to-render-django-form-manually.html#}


{% block main_content_card_body %}
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    {% if selected_loader %}
      <li class="nav-item">
        <a class="nav-link {% if active_tab == 'Run' %}active{% endif %}" id="run-tab" data-toggle="tab" href="#run"
           role="tab" aria-controls="run"
           aria-selected="true">Run</a>
      </li>
    {% endif %}
    <li class="nav-item">
      <a class="nav-link {% if active_tab == 'Configure' %}active{% endif %}" id="configure-tab" data-toggle="tab"
         href="#configure" role="tab" aria-controls="configure"
         aria-selected="false">Configure</a>
    </li>
    {% if selected_loader %}
      <li class="nav-item">
        <a class="nav-link {% if active_tab == 'Attributes' %}active{% endif %}" id="attributes-tab" data-toggle="tab"
           href="#attributes" role="tab" aria-controls="attributes" aria-selected="false">Attributes</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if active_tab == 'Advanced' %}active{% endif %}" id="advanced-tab" data-toggle="tab"
           href="#advanced" role="tab" aria-controls="advanced" aria-selected="false">Advanced</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if active_tab == 'History' %}active{% endif %}" id="history-tab" data-toggle="tab"
           href="#history" role="tab" aria-controls="history"
           aria-selected="false">History</a>
      </li>
    {% endif %}
  </ul>
  <div class="tab-content" id="LoaderTabContent">
    {% if selected_loader %}
      <div class="tab-pane fade pt-3 {% if active_tab == 'Run' %}show active{% endif %}" id="run" role="tabpanel"
           aria-labelledby="run-tab">
        <form id="id_form_run" method="post" action="{% url "loaders:loader_run" current_loader.slug %}">
          <div class="row">
            <div class="col-md-4">
                {% csrf_token %}
                {% include 'core/bs4_form.html' with form=history_form %}
            </div>
            <div class="col-md-8 text-right">
              <button id="btn-run-xoql" data-csrf="{{ csrf_token }}" data-action="{% url "loaders:run_xoql" loader_slug=current_loader.slug %}" class="btn btn-secondary btn-round">Load XOQL Data</button>
              <button id="btn-run" type="submit" class="btn btn-primary btn-round">Run Loader</button>
            </div>
          </div>
        </form>
        {% if not current_loader.attribute_set.all %}Great job, now visit the attributes tab and add some fields.{% endif %}
        <div id="hotData"></div>
      </div>
    {% endif %}
    <div class="tab-pane fade pt-3 {% if active_tab == 'Configure' %}show active{% endif %}" id="configure"
         role="tabpanel"
         aria-labelledby="configure-tab">
      <div class="row">
        <div class="col-md-12 ">

          <form method="post" action="{{ form_action }}">
            {% csrf_token %}
            {% include 'core/bs4_form.html' with form=loader_form %}
            <div class="">
              <button name="btn-loader-submit" type="submit" class="btn btn-primary btn-round">{% if selected_loader %}
                Update{% else %}
                Add{% endif %}</button>
              {% if selected_loader %}
                <button name="btn-cancel" type="submit" class="btn btn-warning btn-round">Cancel</button>
                <button name="btn-archive" type="submit" class="btn btn-danger btn-round">Archive</button>
              {% endif %}
            </div>
          </form>
        </div>

      </div>
    </div>
    {% if selected_loader %}
      <div class="tab-pane fade pt-3 {% if active_tab == 'Attributes' %}show active{% endif %}" id="attributes"
           role="tabpanel" aria-labelledby="attributes-tab">
        <div class="row">
          <div class="col-md-9">
            <table class="table table-hover">
              <thead class=" text-primary">
              <tr>
                <th>Name</th>
                <th>Alias Field</th>
                <th>Type</th>
              </tr>
              </thead>
              <tbody>

              {% for attribute in current_loader.attribute_set.all %}
                <tr {% if attribute == current_attribute %}class="table-active"{% endif %}>
                  <td>
                    {% if attribute.is_key %}<i class="fas fa-key"></i>{% endif %}
                    <strong><a
                      href="{% url "loaders:attribute_edit" current_loader.slug attribute.slug %}">{{ attribute.name }}</a></strong>
                  </td>
                  <td>{{ attribute.alias_field|default_if_none:'' }}</td>
                  <td>{{ attribute.type }}</td>
                </tr>
              {% endfor %}
              </tbody>
            </table>

          </div>
          <div class="col-md-3">
            <h6>Attributes</h6>
            <form method="post" action="{{ attribute_form_action }}">
              {% csrf_token %}
              {% include 'core/bs4_form.html' with form=attribute_form %}
              <div class="">
                <button name="btn-attribute-submit" type="submit" class="btn btn-primary btn-round">
                  {% if current_attribute.pk %}Update{% else %}Add{% endif %}</button>
                {% if current_attribute.pk %}
                  <button name="btn-attribute-cancel" type="submit" class="btn btn-warning btn-round">Cancel</button>
                  <button name="btn-attribute-remove" type="submit" class="btn btn-danger btn-round">Remove</button>
                {% endif %}
              </div>
            </form>
          </div>
        </div>
      </div>
      <div class="tab-pane fade pt-3 {% if active_tab == 'Advanced' %}show active{% endif %}" id="advanced"
           role="tabpanel" aria-labelledby="advanced-tab">
        <div class="row">
          <div class="col-md-4">

            <h6>XOQLs</h6>
            <table class="table table-hover">
              <thead class=" text-primary">
                <tr>
                  <th>Name</th>
                  <th>Description</th>
                </tr>
                </thead>
              <tbody>
              {% for loaderxoql in current_loader.loaderxoql_set.all %}
                <tr {% if loaderxoql == current_loaderxoql %}class="table-active"{% endif %}>
                  <td>
                    <strong><a
                      href="{% url "loaders:loaderxoql_edit" current_loader.slug loaderxoql.slug %}">{{ loaderxoql.name }}</a></strong>
                  </td>
                  <td>{{ loaderxoql.description|default_if_none:'' }}</td>
                </tr>
              {% empty %}
                <tr><td colspan="2">No XOQLs created. Enter the details for the first one in the form to the right. </td></tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          <div class="col-md-8">
            <h6>XOQL</h6>
            <form method="post" action="{{ loaderxoql_form_action }}">
              {% csrf_token %}
              {% include 'core/bs4_form.html' with form=loaderxoql_form %}
              <div class="">
                <button name="btn-loaderxoql-submit" type="submit" class="btn btn-primary btn-round">
                  {% if current_loaderxoql.pk %}Update{% else %}Add{% endif %}</button>
                {% if current_loaderxoql.pk %}
                  <button name="btn-loaderxoql-cancel" type="submit" class="btn btn-warning btn-round">Cancel</button>
                  <button name="btn-loaderxoql-remove" type="submit" class="btn btn-danger btn-round">Remove</button>
                {% endif %}
              </div>
            </form>

          </div>
        </div>
      </div>
      <div class="tab-pane fade {% if active_tab == 'History' %}show active{% endif %}" id="history" role="tabpanel"
           aria-labelledby="history-tab">

      <table class="table">
        <tr>
          <th>Run Date</th>
          <th>Server</th>
          <th>Records</th>
          <th>3e Result</th>
          <th>3e Message</th>
          <th>3e Records</th>
        </tr>
        {% for h in current_loader.history_set.all|slice:":10" %}
        <tr>
          <td><a href="{% url "loaders:loader_history_request" loader_slug=current_loader.slug pk=h.pk %}">{{ h.submitted }}</a></td>
          <td>{{ h.server }}</td>
          <td>{{ h.number_of_records }}</td>
          <td>{{ h.elite_results|default_if_none:"-" }}</td>
          <td>{{ h.elite_message|default_if_none:"-" }}</td>
          <td>{{ h.elite_records|default_if_none:"-" }}</td>
        </tr>
        {% endfor %}
      </table>
      </div>
    {% endif %}
  </div>

{% endblock %}


{% block custom_javascript %}
  <!-- HandsonTables -->

  <script src="https://cdn.jsdelivr.net/npm/handsontable/dist/handsontable.full.min.js"></script>
  <script>
      $(document).ready(function () {

          var data = [[]];
          var container1 = document.getElementById('hotData');
          var hot1 = new Handsontable(container1,
              {
                  data: data,

                  minRows: 1,
                  minCols: {{ current_loader.attribute_set.all.count }},
                  startRows: 5,
                  startCols: 5,
                  stretchH: 'all',
                  manualRowMove: true,
                  manualColumnMove: true,
                  // minSpareRows: 3,
                  columnSorting: true,
                  contextMenu: true,
                  colHeaders: [
                      {% for attribute in current_loader.attribute_set.all %}'{{ attribute.name }}'{% if not forloop.last %}, {% endif %}{% endfor %}
                  ]
              });

          $("#run-tab").on('shown.bs.tab', function () {
              hot1.render();
          });

          toastr.options = {
            "closeButton": true,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-bottom-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "0",
            "extendedTimeOut": "0",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
          };

          function loadxoql(csrf, server, xoql, action) {
              $.ajax({
                  url: action,
                  type: "POST",

                  data: {csrfmiddlewaretoken: csrf,
                         server: server,
                         xoql: xoql,
                         },
                  success: function (data) {
                      console.log(data);
                      if (data.errors) {
                          toastr["error"](data.errors)
                      } else {
                          hot1.loadData(data.data);
                      }
                  }
              });
          }

          $("#btn-run-xoql").on('click', function(e) {
              e.preventDefault();
              // show_loading_modal();
              let csrf = $(this).data("csrf");

              let server = $("#id_server").find(":selected").val();
              let xoql = $("#id_xoql").find(":selected").val();
              let action = $(this).data('action');
              loadxoql(csrf, server, xoql, action);
          });

          $("#id_form_run").submit( function(event) {
              console.log($(this));
              $('<input />').attr('type', 'hidden')
                  .attr('name', "data")
                  .attr('id', "id_data")
                  .attr('value', JSON.stringify({data: hot1.getData()}))
                  .appendTo(this);
              $('<input />').attr('type', 'hidden')
                  .attr('name', "column_headers")
                  .attr('id', "id_column_headers")
                  .attr('value', hot1.getColHeader())
                  .appendTo(this);

              return true;
          });


          $('.textarea-xml').each(function (index, elem) {
              CodeMirror.fromTextArea(elem, {
                  lineWrapping: false,
                  mode: "xml",
                  htmlMode: true,

                  lineNumbers: true,
              });
          });






      });


  </script>


{% endblock %}

proj/junction/loaders/templates/loaders/history_raw.html
{% extends 'base.html' %}
{% load static %}

{% block main_content_card_body %}
  <div class="row">
    <div class="col-md-12">
      <h6>Loader</h6>
      <p><a href="{% url "loaders:loader_edit" history.loader.slug %}">{{ history.loader.name }}</a></p>
      <p class="text-muted">{{ history.loader.description|default_if_none:"" }}</p>
      <h6>Run Time</h6>
      <p>{{ history.submitted }}</p>
      <h6>Server</h6>
      <p>{{ history.server }}</p>

      <h6>Data Column Headers</h6>
      {{ history.column_headers }}

      <h6>Data table</h6>
      <textarea class="form-control textarea-json" data-wrap="false">{{ history.data }}</textarea>


      <h6>Process XML</h6>
      <textarea class="form-control textarea-xml" data-wrap="false">{{ history.process_xml_pretty }}</textarea>

      <h6>Execute Process Response</h6>
      <textarea class="textarea-xml" data-wrap="false">{{ history.response_pretty|safe }}</textarea>


    </div>

  </div>
{% endblock %}



{% block custom_javascript %}
  <script>
      $(document).ready(function () {
          $('.textarea-xml').each(function (index, elem) {
              CodeMirror.fromTextArea(elem, {
                  lineWrapping: $(this).data("wrap"),
                  mode: "xml",
                  htmlMode: true,
                  lineNumbers: true
              });
          });

          $('.textarea-json').each(function (index, elem) {
              CodeMirror.fromTextArea(elem, {
                  lineWrapping: $(this).data("wrap"),
                  mode: {name: "javascript", json: true},
                  htmlMode: true,
                  lineNumbers: true
              });
          });
      });
  </script>
{% endblock %}

proj/junction/loaders/templates/loaders/list.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{#https://simpleisbetterthancomplex.com/article/2017/08/19/how-to-render-django-form-manually.html#}

{% block main_card_header_buttons %}
  <a href="{% url "loaders:loader_edit" %}" class="btn btn-primary btn-round">Add</a>

{% endblock %}

{% block main_content_card_body %}
  <div class="row">
    <div class="col-md-12">
      <table class="table table-hover">
        <thead class=" text-primary">
        <tr>
          <th>
            Name
          </th>
          <th>
            Process
          </th>

          <th>
            Parent Object
          </th>
          <th>
            Parent Action
          </th>
          <th>
            Child Object
          </th>
          <th>
            Child Action
          </th>

        </tr>
        </thead>
        <tbody>

        {% for loader in loaders %}
          <tr {% if loader.pk == selected_loader %}class="table-active"{% endif %}>
            <td><strong><a href="{% url "loaders:loader_edit" loader.slug %}" title="{{ loader.description }}">{{ loader.name }}</a></strong></td>
            <td>{{ loader.process }}</td>
            <td>{{ loader.parent_object }}</td>
            <td>{{ loader.parent_action }}</td>
            <td>{{ loader.child_object|default_if_none:'' }}</td>
            <td>{{ loader.child_action|default_if_none:'' }}</td>


          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>

  </div>
{% endblock %}