proj/elite3eloader/urls.py
from django.contrib import admin
from django.urls import path, include
from junction.core.views import index, junction_license, backup_create, backup


urlpatterns = [
    path('admin/', admin.site.urls),
    path('servers/', include('junction.servers.urls', namespace='servers')),
    path('loaders/', include('junction.loaders.urls', namespace='loaders')),
    path('license/', junction_license, name='license'),
    path('backup/', backup, name='backup'),
    path('backup-create/', backup_create, name='backup_create'),
    path('', index, name='index'),
]

proj/junction/loaders/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright 2018 Junction Applications
# Author: Aaron MacGillivary
# Project: elite3eloader

from . import views
from django.urls import path

app_name = 'loaders'

urlpatterns = [
    path('', views.loader_list, name='loader_list'),
    path('new/', views.loader_edit, name='loader_edit'),
    path('<slug:loader_slug>/run', views.loader_run, name='loader_run'),
    path('<slug:loader_slug>', views.loader_edit, name='loader_edit'),
    path('<slug:loader_slug>/tab/attributes/', views.loader_edit, {'active_tab': 'Attributes'},  name='loader_attribute_active'),
    path('<slug:loader_slug>/tab/advanced/', views.loader_edit, {'active_tab': 'Advanced'},  name='loader_advanced_active'),
    path('<slug:loader_slug>/attribute/<slug:attribute_slug>', views.loader_edit, name='attribute_edit'),
    path('<slug:loader_slug>/xoql/<slug:loaderxoql_slug>', views.loader_edit, name='loaderxoql_edit'),
    path('<slug:loader_slug>/history/request/<int:pk>', views.history_raw, name='loader_history_request'),
    path('<slug:loader_slug>/runxoql/', views.run_xoql, name='run_xoql'),

]

proj/junction/servers/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright 2018 Junction Applications
# Author: Aaron MacGillivary
# Project: elite3eloader

from . import views
from django.urls import path

app_name = 'servers'

urlpatterns = [
    path('', views.list, name='server_list'),
    path('<slug:server_slug>', views.list, name='server_edit'),

]

proj/junction/core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    """ Custom user based on Django best practices
    https://docs.djangoproject.com/en/2.1/topics/auth/customizing/#using-a-custom-user-model-when-starting-a-project
    """

    def __init__(self, *args, **kwargs):
        super(User, self).__init__(*args, **kwargs)


class UserProfile(models.Model):
    """ Holds profile details for this user """
    pass


class License(models.Model):
    """ Holds the date the license was agreed to """
    agreed = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.agreed}"

proj/junction/core/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright 2018 Junction Applications
# Author: Aaron MacGillivary
# Project: elite3eloader

from django import forms

from junction.core.models import License


class UploadRestoreForm(forms.Form):
    restorefile = forms.FileField(label="Select a restore file (*.json)",
                                  widget=forms.FileInput(attrs={'accept': '.json'}))


class LicenseForm(forms.ModelForm):

    class Meta:
        model = License
        exclude = ['agreed', ]

proj/junction/core/views.py
import os
import sys

from django.shortcuts import render
from django.core import management
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.core.files.storage import FileSystemStorage
from django.urls import reverse

from junction.core.forms import UploadRestoreForm, LicenseForm
from junction.core.models import License


def index(request):

    license_check = License.objects.all().exists()
    if not license_check:
        redirect_url = reverse('license')
        return redirect(redirect_url)

    context = {'active_side_bar': 'dashboard',
               'main_content_card_title': 'Welcome',
               'main_content_card_subtitle': 'Work in Progress - Beta Software',
               'main_content_card_footer': '', }

    return render(request, 'core/dashboard.html', context)


def junction_license(request):
    """ Shows the initial license form, and shows license without
    the form if it has already been agreed to.
    """
    if request.method == 'POST':
        license_form = LicenseForm(request.POST)
        if license_form.is_valid():
            license_form.save()
            redirect_url = reverse('index')
            return redirect(redirect_url)

    # check if the license has been agreed to
    license_check = License.objects.all().exists()

    if license_check:
        show_license_form = False
    else:
        show_license_form = True

    context = {'active_side_bar': 'license',
               'main_content_card_title': 'License',
               'main_content_card_subtitle': 'MIT License',
               'main_content_card_footer': '',
               'show_license_form': show_license_form, }

    return render(request, 'core/license.html', context)


def backup(request):
    license_check = License.objects.all().exists()
    if not license_check:
        redirect_url = reverse('license')
        return redirect(redirect_url)

    error_text = False
    if request.method == 'POST':
        restore_form = UploadRestoreForm(request.POST, request.FILES)
        if restore_form.is_valid():
            f = request.FILES['restorefile']
            fs = FileSystemStorage()
            saved_as = fs.save(f.name, f)
            try:
                management.call_command('loaddata', os.path.join(fs.location, saved_as), verbosity=0)
            except management.CommandError:
                error_text = ["There was an issue restoring from that file.",
                              "The restore has failed. Verify the file is valid and try again."]
            else:
                redirect_url = reverse('loaders:loader_list')

            try:
                os.remove(os.path.join(fs.location, saved_as))
            except OSError:
                pass
            if not error_text:
                return redirect(redirect_url)
    else:
        restore_form = UploadRestoreForm()

    context = {'active_side_bar': 'backup',
               'main_content_card_title': 'Backup/Restore',
               'main_content_card_subtitle': 'Create a backup prior to update, and restore after an update',
               'main_content_card_footer': '',
               'restore_form': restore_form,
               'error_text': error_text,
               }

    return render(request, 'core/backup-restore.html', context)


def backup_create(request):
    """ Saves a copy of the server, loader, attribute and history models, saves to a file
    and should prompt user to save it somewhere. """

    license_check = License.objects.all().exists()
    if not license_check:
        redirect_url = reverse('license')
        return redirect(redirect_url)

    sysout = sys.stdout
    response = HttpResponse(content_type='application/json')
    response['Content-Disposition'] = 'attachment; filename=backup.json'
    sys.stdout = response
    management.call_command('dumpdata', 'core', 'loaders', 'servers')
    sys.stdout = sysout
    return response

proj/junction/core/templates/core/backup-restore.html
{% extends "base.html" %}

{% block main_content_card_body %}
<dl>
<dt>Backup</dt>
<dd>
<p>This will create a file in JSON format storing all of the server, loaders, and core configurations. </p><p>Save this file in a place other than the directory of this application. We'll use the file after an update to restore any loaders you have created.</p>
<a class="btn btn-primary" href="{% url "backup_create" %}">Backup</a></dd>

<dt>Restore</dt>
<dd>
  <p>Select a previously created backup to restore data from and press restore. <strong>This will overwrite existing data.</strong></p>
  {% if error_text %}
    <div class="alert alert-danger row" role="alert">
    <div class="col-sm-2"><i class="fas fa-exclamation-circle fa-5x"></i></div>
      <div class="col-sm-10"><strong>{{ error_text.0 }}</strong><p>{{ error_text.1 }}</p></div>

    </div>
  {% endif %}
  <form method="post" action="{% url "backup" %}" enctype="multipart/form-data">
  {% csrf_token %}
  {% include 'core/bs4_form.html' with form=restore_form %}
  <button type="submit" class="btn btn-warning">Restore</button>

  </form>
</dd>
</dl>


{% endblock  %}

proj/junction/core/templates/core/bs4_form.html
{% load widget_tweaks %}
{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      {{ error }}
    {% endfor %}
  </div>
{% endif %}

{% for field in form.visible_fields %}
  <div class="form-group">
    {{ field.label_tag }}

    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class+="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% if forloop.first %}
          {% render_field field class+="form-control is-valid" %}
        {% else %}
          {% render_field field class+="form-control is-valid" %}
        {% endif %}
      {% endif %}
    {% else %}
      {% render_field field class+="form-control" %}
    {% endif %}

    {% if field.help_text %}
      <small class="form-text text-muted">{{ field.help_text }}</small>
    {% endif %}
  </div>
{% endfor %}

proj/junction/core/templates/core/dashboard.html
{% extends "base.html" %}
{% block main_content_card_body %}
  <p>This is fairly quick first pass at putting together a data loader for Elite 3E. It has
    been tested on 2.8.3 but may work for versions back to 2.6. Limited functional testing has
    been completed, however, as everyone's setup is a little bit different, I expect some
    issues will arise. Report issues through the Github repository. </p>
  <p> This was a quick first pass at this and is meant more as a proof of concept than finished software.
    There is definitely room for improvement.</p>
  <p>Create the servers (UAT, PROD, DEV). If you leave the domain, username &amp: password blank and are
    running this app on your local machine, your local credentials will be used, otherwise the app will use the
    credentials entered on the server setup. </p>
  <p>Create loaders for
    anything you need to load data into. For an example, the app will ship with one loader
    which adds some vendors (which could be useful after a merger). </p>
  <p>You can create as many loaders as you like. First create the loader and provide the basic
    info, then add the attributes as needed. You can create loaders which create top level objects,
    or edit existing top level objects (you cannot mix and match in one loader). </p>
  <p>This application is meant to be run locally by the user doing the updates. It can be
    configured to be hosted on a proper server, but then we get into having to either ask for
    network passwords, or operate as a system account. Running locally on a user's workstation
    allows us to make the requests on that user's behalf and be restricted to that user's
    permissions (unless the credentials are provided in the server setup). Passwords entered in the
    server setup are not encrypted.</p>


{% endblock %}

proj/junction/core/templates/core/input.html
{% comment %}
## THERE IS A BOOTSTRAP LIBRARY TO DO ALMOST THE EXACT SAME THING BUT I DON'T LIKE IT ##
input type="text"
       name="{{ form.name.name }}"
       id="{{ form.name.id_for_label }}"
       {% if form.name.value != None %}value="{{ form.name.value|stringformat:'s' }}"{% endif %}
       maxlength="{{ form.name.field.max_length }}"
       {% if form.name.field.required %}required{% endif %}>
{% endcomment %}
{{ form_ctrl }}
<div class="form-group">
  <label for="{{ frm_ctrl.id_for_label }}">{{ frm_ctrl.label }}</label>
  <input type="text"
         name="{{ frm_ctrl.name }}"
         id="{{ frm_ctrl.id_for_label }}"
         maxlength="{{ frm_ctrl.field.max_length }}"
         class="form-control"
         {% if frm_ctrl.value != None %}value="{{ frm_ctrl.value|stringformat:'s' }}"{% endif %}

         {% for n, v in frm_ctrl.widget.attrs.items %}
          {% if v is not False %}
            {{ n }}{% if v is not True %}="{{ v|stringformat:'s' }}"{% endif %}
          {% endif %}
        {% endfor %}
  >
  {% if frm_ctrl.help_text %}
  <small id="{{ frm_ctrl.name }}Help" class="form-text text-muted">{{ frm_ctrl.help_text }}</small>
  {% endif %}
</div>

proj/junction/core/templates/core/license.html
{% extends "base.html" %}

{% block main_content_card_body %}
<p>Copyright {% now "Y" %} Junction Applications Limited</p>

<p>Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:</p>

<p>The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.</p>

  <p><strong>THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.</strong></p>

  {% if show_license_form %}
    <form method="post" action="{% url "license" %}">
      {% csrf_token %}
      <button type="submit" class="btn btn-primary">I agree to the License</button>
    </form>
  {% endif %}

{% endblock  %}

proj/junction/core/templates/core/main-content.html
{#currently unused, may get picked up again if we move to ajax calls for the navigation#}
<div class="row">
  <div class="col-md-12">
    <div class="card ">
      <div class="card-header ">
        <h5 class="card-title">{{ main_content_card_title }}</h5>
        <p class="card-category">{{ main_content_card_subtitle }}</p>
      </div>
      <div class="card-body ">
{% block main_content_card_body %}{% endblock %}
      </div>
      <div class="card-footer ">
        <hr>
        <div>
          <p class="card-description">{{ main_content_card_footer }}</p>
        </div>
      </div>
    </div>
  </div>
</div>

proj/junction/core/templates/core/main-navbar.html
<div class="container-fluid">
  <div class="navbar-wrapper">
    <div class="navbar-toggle">
      <button type="button" class="navbar-toggler"><i class="fas fa-bars"></i></button>
    </div>
    <a class="navbar-brand" href="{% url 'index' %} ">3E Loader</a>
  </div>
</div>

proj/junction/core/templates/core/sidebar-menu.html
<ul class="nav">
{% if not show_license_form|default_if_none:False %}
  <li {% if active_side_bar == 'dashboard' %}class="active"{% endif %}>
    <a href="/">
      <i class="fas fa-home"></i>
      <p>Dashboard</p>
    </a>
  </li>
  <li {% if active_side_bar == 'loaders' %}class="active"{% endif %}>
    <a href="{% url "loaders:loader_list" %}">
      <i class="fas fa-upload"></i>
      <p>Loaders</p>
    </a>
  </li>
  <li {% if active_side_bar == 'servers' %}class="active"{% endif %}>
    <a href="{% url "servers:server_list" %}">
      <i class="fas fa-server"></i>
      <p>Servers</p>
    </a>
  </li>
  <li {% if active_side_bar == 'backup' %}class="active"{% endif %}>
    <a href="{% url "backup" %}">
      <i class="fas fa-window-restore"></i>
      <p>Backup/Restore</p>
    </a>
  </li>
{% endif %}
  <li {% if active_side_bar == 'license' %}class="active"{% endif %}>
    <a href="{% url "license" %}">
      <i class="fas fa-file-contract"></i>
      <p>License</p>
    </a>
  </li>

</ul>